---
#VM Settings
ip: 192.168.100.42
memory: 2048
cpus: 1
provider: virtualbox

# Authorisation
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa

#Folders
folders:
#    - map: ./application
#      to: /application
    - map: ./vagrant
      to: /vagrant

#Database
#databases:
#    - name: application
#      type: mysql

#server name
name: vm.test

#Sites
sites:
    - map: vm
      type: ignore
      function: startpage
      desc: "Startpage"
    - map: profiler.vm
      type: ignore
      function: profiler
      desc: "Profiler Server"
    - map: pma.vm
      type: ignore
      function: pma
      desc: "PHP MyAdmin Server"
    - map: rabbit.vm
      type: ignore
      function: rabbit
      desc: "Rabbit MQ Server"
    - map: search.vm
      type: ignore
      function: search
      desc: "Elastic Search Server"
    - map: kibana.vm
      type: ignore
      function: kibana
      desc: "Kibana Server"
    - map: mail.vm
      type: ignore
      function: mail
      desc: "Mail Server"
    - map: cockpit.vm
      type: ignore
      function: cockpit
      desc: "Cockpit"
    - map: ui.vm
      type: ignore
      function: ui
      desc: "Docker UI Server"
    - map: build.vm
      type: ignore
      function: build
      desc: "Build Server"
    - map: info72.vm
      type: ignore
      function: phpinfo
      desc: "PHP Info 7.2"
    - map: info71.vm
      type: ignore
      function: phpinfo
      desc: "PHP Info 7.1"
    - map: info70.vm
      type: ignore
      function: phpinfo
      desc: "PHP Info 7.0"
    - map: info56.vm
      type: ignore
      function: phpinfo
      desc: "PHP Info 5.6"
    - map: darkstat.vm
      type: ignore
      function: darkstat
      desc: "DarkStat"

#Features
php72: true
php: true
nginx: true