---
ip: 192.168.100.42
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa

folders:
    - map: ./application
      to: /application
    - map: ./vagrant
      to: /vagrant

databases:
    - application

name: vm.test
