---
ip: 192.168.100.42
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa

folders:
    - map: ./application
      to: /application
    - map: ./vagrant
      to: /vagrant

databases:
    - application

name: vm.test

sites:
    - map: profiler.registration.test
      type: ignore
    - map: pma.registration.test
      type: ignore
    - map: info.registration.test
      type: ignore
    - map: rabbit.registration.test
      type: ignore
    - map: search.registration.test
      type: ignore
    - map: kibana.registration.test
      type: ignore
    - map: mail.registration.test
      type: ignore
    - map: cockpit.registration.test
      type: ignore
    - map: ui.registration.test
      type: ignore