---
#VM Settings
ip: 192.168.100.42
memory: 2048
cpus: 1
provider: virtualbox

# Authorisation
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa

#Folders
folders:
#    - map: ./application
#      to: /application
    - map: ./vagrant
      to: /vagrant

#Database
#databases:
#    - name: application
#      type: mysql

#server name
name: vm.test

#Sites
sites:
    - map: vm
      type: ignore
      function: startpage
      desc: "Startpage"

#Features
features:
    php72: true
    php: true
    nginx: true