#!/usr/bin/env bash
angular/build.sh
blackfire/build.sh
classic/build.sh
elasticsearch/build.sh
errbit/build.sh
kibana/build.sh
logstash/build.sh
mailhog/build.sh
mongodb/build.sh
nginx/build.sh
nginxApp/build.sh
phpCli/build.sh
phpcronsupervisor/build.sh
phpFpm/build.sh
phpScheduler/build.sh
portainer/build.sh
rabbitmq/build.sh
redis/build.sh
vault/build.sh
xhgui/build.sh